name: Scrape cros-updates-serving

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    paths:
      - ".github/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Scraping
        run: |
          npm install tabletojson json2csv
          npm run scrape
        env:
          CI: true
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_BRANCH: "master"
